version: '3.8'

services:
  llm:
    build:
      context: .
      dockerfile: llm.cpu.Dockerfile
    ports:
      - "30000:30000"
    networks:
      - default

  kokoro:
    build:
      context: .
      dockerfile: kokoro.cpu.Dockerfile
    ports:
      - "8880:8880"
    networks:
      - default

  conversify:
    build:
      context: .
      dockerfile: conversify.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - llm
      - kokoro
    volumes:
      - ./config.cpu.yaml:/app/config.yaml
      - .:/app
    env_file:
      - .env.local
    networks:
      - default

networks:
  default:
    driver: bridge
